//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    
    public partial class Schedule
    {
        //public IEnumerable<HttpPostedFileBase> Files { get; set; }

        public int Schedule_ID { get; set; }
        //public int[] Schedule_ID { get; set; }
        public int Subject_ID { get; set; }
        public int Room_ID { get; set; }
        public int Lesson_ID { get; set; }

        

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString =
           "{0:yyyy-MM-dd}",
            ApplyFormatInEditMode = true)]
        public System.DateTime? Date { get; set; }
        
        public int Group_ID { get; set; }
        public int Teacher_ID { get; set; }
                       
    
        public virtual Classroom Classroom { get; set; }
        public virtual Group Group { get; set; }
        public virtual LessonType LessonType { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual Teacher Teacher { get; set; }
        public string EnrollmentYear { get; set; }
        public string LessonNumber { get; set; }

        
    }
}
